title: Raymond's Blog
author: Raymond Hu
email: raymond.hu23.553@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"

# social links
twitter_username: RaymondHu3 # DO NOT include the @ character, or else the build will fail!
github_username: RaymondHu23 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
